#!/bin/sh

MANTICORE_ROOT=/Applications/Manticore
MAX5_JAVA_ROOT=/Applications/Max5/Cycling\ \'74/java

# Backup Java config file of Max
cp -v "$MAX5_JAVA_ROOT"/max.java.config.txt "$MAX5_JAVA_ROOT"/max.java.config.bkp

# Apply changes assuming Manticore is installed in $MANTICORE_ROOT
sed -i "" '19c\
	max.dynamic.class.dir '$MANTICORE_ROOT'/projects/MAX/max_externals/bin/\
		' "$MAX5_JAVA_ROOT"/max.java.config.txt
sed -i "" '22c\
	max.dynamic.class.dir '$MANTICORE_ROOT'/projects/MAX/max_externals/lib/\
	' "$MAX5_JAVA_ROOT"/max.java.config.txt

exit 0